# Generated by Django 4.0.4 on 2022-04-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Napster', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pic/default.jpg', upload_to='profile_pic'),
        ),
    ]
