# Generated by Django 4.0.4 on 2022-04-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('artist', models.CharField(max_length=300)),
                ('album', models.CharField(max_length=300)),
                ('song_art', models.ImageField(upload_to='images/')),
                ('song_file', models.FileField(blank=True, null=True, upload_to='')),
                ('song_length', models.CharField(max_length=300)),
                ('song_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
