# Generated by Django 4.0.4 on 2022-04-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Napster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='song_file',
            new_name='audio_file',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='song_link',
            new_name='audio_link',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='song_art',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
        migrations.RemoveField(
            model_name='music',
            name='song_length',
        ),
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.TextField(),
        ),
    ]
