# Generated by Django 4.0.4 on 2022-04-13 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Napster', '0002_rename_song_file_music_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameField(
            model_name='music',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='duration',
            new_name='music_duration',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='audio_file',
            new_name='music_file',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='audio_link',
            new_name='music_link',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='title',
            new_name='music_title',
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Napster.album'),
        ),
    ]
